<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f3d42003-17ac-4871-8551-5839d9ec9faa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="NPOI" Version="2.7.5" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>

</Project>
